Importing the Dependencies

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

Importing the models

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

Data Collection and Processing

In [3]:
#loading the csv data to a pandas datafram
heart_data=pd.read_csv('/content/heart_disease_data.csv')

In [4]:
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [10]:
#no of rows in the dataset
heart_data.shape

(303, 14)

In [9]:
#checking for missing values
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
#checking the distribution of target variable
heart_data.value_counts('target')

target
1    165
0    138
Name: count, dtype: int64

1--> Defective heart

0-->Healthy heart

Splitting the Feature and Target

In [11]:
X=heart_data.drop(columns='target',axis=1)
Y=heart_data['target']

In [12]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [13]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

#Train Test Split

In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=3)

In [18]:
print(X.shape,X_train.shape,X_test.shape)

(303, 13) (242, 13) (61, 13)

Comparing the Performance of the models

In [22]:
#list of models
models=[LogisticRegression(max_iter=1000),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [23]:
def compare_models_train_test():
  for model in models:
    #training the model
    model.fit(X_train,Y_train)
    #evaluating the model
    test_data_prediction=model.predict(X_test)
    accuracy=accuracy_score(Y_test,test_data_prediction)
    print('Accuracy Of the models:',model,'=',accuracy)

In [24]:
compare_models_train_test()

Accuracy Of the models: LogisticRegression(max_iter=1000) = 0.7868852459016393
Accuracy Of the models: SVC(kernel='linear') = 0.7704918032786885
Accuracy Of the models: KNeighborsClassifier() = 0.6557377049180327
Accuracy Of the models: RandomForestClassifier() = 0.8032786885245902

#Cross Validation

Logistic Regression

In [29]:
cv_score_lr=cross_val_score(LogisticRegression(max_iter=1000),X,Y,cv=5)
print(cv_score_lr)
mean_accuracy_lr=sum(cv_score_lr)/len(cv_score_lr)
mean_accuracy_lr=mean_accuracy_lr*100
mean_accuracy_lr=round(mean_accuracy_lr,2)
print(mean_accuracy_lr)

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
82.83

Support Vector Classifier

In [30]:
cv_score_svc=cross_val_score(SVC(kernel='linear'),X,Y,cv=5)
print(cv_score_svc)
mean_accuracy_svc=sum(cv_score_svc)/len(cv_score_svc)
mean_accuracy_svc=mean_accuracy_svc*100
mean_accuracy_svc=round(mean_accuracy_svc,2)
print(mean_accuracy_svc)

[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
82.83

Creating a function to compare the models

In [31]:
#list of models
models=[LogisticRegression(max_iter=1000),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [35]:
def compare_models_cross_validation():
  for model in models:
    cv_score=cross_val_score(model,X,Y,cv=5)
    mean_accuracy=sum(cv_score)/len(cv_score)
    mean_accuracy=mean_accuracy*100
    mean_accuracy=round(mean_accuracy,2)
    print('Cross Validation accuracies for the',model,'=',cv_score)
    print('Accuracy % of the',model,mean_accuracy)
    print('--------------------------')

In [36]:
compare_models_cross_validation()

Cross Validation accuracies for the LogisticRegression(max_iter=1000) = [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
Accuracy % of the LogisticRegression(max_iter=1000) 82.83
--------------------------
Cross Validation accuracies for the SVC(kernel='linear') = [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
Accuracy % of the SVC(kernel='linear') 82.83
--------------------------
Cross Validation accuracies for the KNeighborsClassifier() = [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
Accuracy % of the KNeighborsClassifier() 64.39
--------------------------
Cross Validation accuracies for the RandomForestClassifier() = [0.83606557 0.90163934 0.81967213 0.8        0.78333333]
Accuracy % of the RandomForestClassifier() 82.81
--------------------------